"""
Base Strategy Template
All strategies inherit from this class.
"""
from abc import ABC, abstractmethod
from typing import Dict, List, Optional
import pandas as pd


class BaseStrategy(ABC):
    """Abstract base for all trading strategies."""

    def __init__(self, name: str, config: Optional[Dict] = None):
        self.name = name
        self.config = config or {}
        self.metadata = {
            "name": name,
            "version": "1.0",
            "author": "TradingTerminal",
            "description": "",
            "timeframes": ["M1"],
            "symbols": [],
            "risk_per_trade": 0.5,
        }

    @abstractmethod
    def signal(self, df: pd.DataFrame, open_positions: list,
               params: Optional[Dict] = None) -> Dict:
        """
        Generate trading signal from market data.
        Returns dict with 'signal': 'buy' | 'sell' | 'hold' | 'close'
        """
        ...

    def get_parameters(self) -> Dict:
        return {**self.metadata.get("DEFAULT_PARAMS", {}), **self.config}

    def export_mql5(self) -> str:
        """Export strategy as MQL5 Expert Advisor template."""
        return f"""//+------------------------------------------------------------------+
//| {self.name} EA - Auto-generated by Trading Terminal             |
//+------------------------------------------------------------------+
#property copyright "Trading Terminal"
#property version   "1.0"

// Strategy Parameters
input int    FastEMA     = {self.config.get('fast_ema', 8)};
input int    SlowEMA     = {self.config.get('slow_ema', 21)};
input double RiskPct     = {self.config.get('risk_pct', 0.5)};
input double ATR_SL_Mult = {self.config.get('atr_sl_mult', 1.5)};
input double ATR_TP_Mult = {self.config.get('atr_tp_mult', 2.5)};

int OnInit() {{
   Print("Strategy: {self.name} initialized");
   return(INIT_SUCCEEDED);
}}

void OnTick() {{
   // Strategy logic generated from Python
   // See backend/strategies for full implementation
}}
"""

    def export_python(self) -> str:
        """Export strategy as standalone Python script."""
        return f'''"""
{self.name} - Exported from Trading Terminal
"""
import pandas as pd
from backend.strategies.base_strategy import BaseStrategy
from backend.core.indicators import Indicators

class {self.name.replace(" ", "")}(BaseStrategy):
    DEFAULT_PARAMS = {self.config}
    
    def __init__(self, config=None):
        super().__init__("{self.name}", config)
    
    def signal(self, df, open_positions, params=None):
        # Implementation exported from Trading Terminal
        pass
'''
