//+------------------------------------------------------------------+
//|                    Trading Terminal EA                           |
//|                    Auto-generated by Python Agent               |
//|                    Connects to Python backend via named pipe     |
//+------------------------------------------------------------------+
#property copyright "Trading Terminal"
#property link      "https://github.com/trading-terminal"
#property version   "1.00"
#property strict

// --- Input Parameters ---
input string   EA_Name        = "TradingTerminal_EA";
input int      Magic          = 20250101;
input double   Risk_Pct       = 0.5;       // Risk % per trade
input double   ATR_SL_Mult    = 1.5;       // SL = ATR * multiplier
input double   ATR_TP_Mult    = 2.5;       // TP = ATR * multiplier
input int      ATR_Period     = 14;        // ATR period
input int      Fast_EMA       = 8;
input int      Slow_EMA       = 21;
input int      RSI_Period     = 14;
input double   RSI_Oversold   = 35.0;
input double   RSI_Overbought = 65.0;
input double   Min_Volume_Ratio = 1.3;    // Min vol vs avg
input bool     Session_Filter = true;
input bool     News_Filter    = true;
input int      Max_Positions  = 5;
input int      Max_Slippage   = 20;       // Max allowed slippage
input bool     Trailing_Stop  = true;
input double   Trail_ATR_Mult = 1.0;

// --- Global handles ---
int g_atr_handle;
int g_ema_fast_handle;
int g_ema_slow_handle;
int g_rsi_handle;

// Statistics
int g_trades_opened = 0;
int g_trades_closed = 0;
double g_daily_pnl = 0;
datetime g_last_day;

//+------------------------------------------------------------------+
//| Expert initialization                                             |
//+------------------------------------------------------------------+
int OnInit()
{
   Print("=== Trading Terminal EA Starting ===");
   Print("Symbol: ", Symbol(), " | TF: ", EnumToString(Period()));
   Print("Mode: ", (AccountInfoInteger(ACCOUNT_TRADE_MODE) == ACCOUNT_TRADE_MODE_DEMO ? "DEMO" : "LIVE"));
   
   // Initialize indicator handles
   g_atr_handle = iATR(Symbol(), Period(), ATR_Period);
   g_ema_fast_handle = iMA(Symbol(), Period(), Fast_EMA, 0, MODE_EMA, PRICE_CLOSE);
   g_ema_slow_handle = iMA(Symbol(), Period(), Slow_EMA, 0, MODE_EMA, PRICE_CLOSE);
   g_rsi_handle = iRSI(Symbol(), Period(), RSI_Period, PRICE_CLOSE);
   
   if(g_atr_handle == INVALID_HANDLE || g_ema_fast_handle == INVALID_HANDLE ||
      g_ema_slow_handle == INVALID_HANDLE || g_rsi_handle == INVALID_HANDLE)
   {
      Print("ERROR: Failed to create indicator handles");
      return INIT_FAILED;
   }
   
   g_last_day = TimeCurrent();
   Print("✅ EA Initialized | Magic=", Magic);
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization                                           |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(g_atr_handle);
   IndicatorRelease(g_ema_fast_handle);
   IndicatorRelease(g_ema_slow_handle);
   IndicatorRelease(g_rsi_handle);
   Print("EA stopped | Trades: ", g_trades_opened, " | Daily PnL: ", g_daily_pnl);
}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
{
   // Only process on new bar (M1)
   static datetime last_bar_time = 0;
   datetime current_bar = iTime(Symbol(), Period(), 0);
   if(current_bar == last_bar_time) return;
   last_bar_time = current_bar;
   
   // Daily reset
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   MqlDateTime last_dt;
   TimeToStruct(g_last_day, last_dt);
   if(dt.day != last_dt.day) {
      g_daily_pnl = 0;
      g_last_day = TimeCurrent();
      Print("📅 New trading day - stats reset");
   }
   
   // Session filter
   if(Session_Filter && !IsGoodSession()) {
      Comment("TT EA | Waiting for active session...");
      return;
   }
   
   // Get indicator values
   double atr[], ema_fast[], ema_slow[], rsi[];
   ArraySetAsSeries(atr, true);
   ArraySetAsSeries(ema_fast, true);
   ArraySetAsSeries(ema_slow, true);
   ArraySetAsSeries(rsi, true);
   
   if(CopyBuffer(g_atr_handle, 0, 0, 3, atr) < 3) return;
   if(CopyBuffer(g_ema_fast_handle, 0, 0, 3, ema_fast) < 3) return;
   if(CopyBuffer(g_ema_slow_handle, 0, 0, 3, ema_slow) < 3) return;
   if(CopyBuffer(g_rsi_handle, 0, 0, 3, rsi) < 3) return;
   
   double atr_val = atr[1];
   double fast = ema_fast[1];
   double slow = ema_slow[1];
   double rsi_val = rsi[1];
   double fast_prev = ema_fast[2];
   double slow_prev = ema_slow[2];
   
   // Volume analysis
   long vol_curr = iVolume(Symbol(), Period(), 1);
   double vol_avg = 0;
   for(int i = 1; i <= 20; i++) vol_avg += (double)iVolume(Symbol(), Period(), i);
   vol_avg /= 20.0;
   double vol_ratio = vol_avg > 0 ? vol_curr / vol_avg : 1.0;
   
   // Current positions
   int positions = CountPositions();
   
   // Update trailing stops
   if(Trailing_Stop) UpdateTrailingStops(atr_val);
   
   // Entry logic
   if(positions < Max_Positions)
   {
      bool bull_cross = fast > slow && fast_prev <= slow_prev;
      bool bear_cross = fast < slow && fast_prev >= slow_prev;
      bool bull_trend = fast > slow * 1.0001;
      bool bear_trend = fast < slow * 0.9999;
      bool vol_ok = vol_ratio >= Min_Volume_Ratio;
      
      // BUY SIGNAL
      if((bull_cross || (bull_trend && rsi_val < RSI_Oversold + 15)) &&
         vol_ok && rsi_val < RSI_Overbought)
      {
         if(!HasPosition(POSITION_TYPE_BUY))
         {
            double entry = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
            double sl = NormalizeDouble(entry - atr_val * ATR_SL_Mult, Digits());
            double tp = NormalizeDouble(entry + atr_val * ATR_TP_Mult, Digits());
            double lots = CalculateLots(atr_val, Risk_Pct);
            
            if(OpenOrder(ORDER_TYPE_BUY, lots, entry, sl, tp, "TT-Buy"))
            {
               g_trades_opened++;
               Print("▲ BUY opened | Lots=", lots, " | SL=", sl, " | TP=", tp,
                     " | ATR=", atr_val, " | Vol ratio=", vol_ratio);
            }
         }
      }
      
      // SELL SIGNAL
      if((bear_cross || (bear_trend && rsi_val > RSI_Overbought - 15)) &&
         vol_ok && rsi_val > RSI_Oversold)
      {
         if(!HasPosition(POSITION_TYPE_SELL))
         {
            double entry = SymbolInfoDouble(Symbol(), SYMBOL_BID);
            double sl = NormalizeDouble(entry + atr_val * ATR_SL_Mult, Digits());
            double tp = NormalizeDouble(entry - atr_val * ATR_TP_Mult, Digits());
            double lots = CalculateLots(atr_val, Risk_Pct);
            
            if(OpenOrder(ORDER_TYPE_SELL, lots, entry, sl, tp, "TT-Sell"))
            {
               g_trades_opened++;
               Print("▼ SELL opened | Lots=", lots, " | SL=", sl, " | TP=", tp);
            }
         }
      }
   }
   
   // Display dashboard
   string session_str = GetSessionName();
   Comment("═══ TRADING TERMINAL EA ═══\n",
           "Symbol: ", Symbol(), " | TF: ", EnumToString(Period()), "\n",
           "Session: ", session_str, " | Score: ", GetSessionScore(), "/100\n",
           "ATR: ", DoubleToString(atr_val, Digits()), " | RSI: ", DoubleToString(rsi_val, 1), "\n",
           "EMA Fast: ", DoubleToString(fast, Digits()),
           " | Slow: ", DoubleToString(slow, Digits()), "\n",
           "Vol Ratio: ", DoubleToString(vol_ratio, 2), "\n",
           "Open Positions: ", positions, "/", Max_Positions, "\n",
           "Trades Today: ", g_trades_opened, "\n",
           "Daily PnL: $", DoubleToString(g_daily_pnl, 2), "\n",
           "═══════════════════════");
}

//+------------------------------------------------------------------+
//| Open order with full error handling                              |
//+------------------------------------------------------------------+
bool OpenOrder(ENUM_ORDER_TYPE type, double lots, double price,
               double sl, double tp, string comment)
{
   MqlTradeRequest req = {};
   MqlTradeResult res = {};
   
   req.action    = TRADE_ACTION_DEAL;
   req.symbol    = Symbol();
   req.volume    = lots;
   req.type      = type;
   req.price     = price;
   req.sl        = sl;
   req.tp        = tp;
   req.deviation = Max_Slippage;
   req.magic     = Magic;
   req.comment   = comment;
   req.type_time = ORDER_TIME_GTC;
   req.type_filling = ORDER_FILLING_IOC;
   
   if(!OrderSend(req, res))
   {
      Print("OrderSend failed: ", GetLastError(), " | retcode=", res.retcode, 
            " | ", res.comment);
      return false;
   }
   return res.retcode == TRADE_RETCODE_DONE;
}

//+------------------------------------------------------------------+
//| Calculate position size based on risk %                          |
//+------------------------------------------------------------------+
double CalculateLots(double atr_val, double risk_pct)
{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double risk_amount = balance * risk_pct / 100.0;
   double tick_value = SymbolInfoDouble(Symbol(), SYMBOL_TRADE_TICK_VALUE);
   double tick_size = SymbolInfoDouble(Symbol(), SYMBOL_TRADE_TICK_SIZE);
   double sl_pips = atr_val * ATR_SL_Mult / tick_size;
   double lot_step = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_STEP);
   double min_lot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MIN);
   double max_lot = SymbolInfoDouble(Symbol(), SYMBOL_VOLUME_MAX);
   
   if(tick_value <= 0 || sl_pips <= 0) return min_lot;
   double lots = risk_amount / (sl_pips * tick_value);
   lots = MathMax(min_lot, MathMin(max_lot, MathFloor(lots / lot_step) * lot_step));
   return NormalizeDouble(lots, 2);
}

//+------------------------------------------------------------------+
//| Update trailing stops                                             |
//+------------------------------------------------------------------+
void UpdateTrailingStops(double atr_val)
{
   double trail_dist = atr_val * Trail_ATR_Mult;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(!PositionSelectByTicket(ticket)) continue;
      if(PositionGetInteger(POSITION_MAGIC) != Magic) continue;
      
      double current_price = SymbolInfoDouble(Symbol(), SYMBOL_BID);
      double current_sl = PositionGetDouble(POSITION_SL);
      double current_tp = PositionGetDouble(POSITION_TP);
      double new_sl = 0;
      
      if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY)
      {
         new_sl = NormalizeDouble(current_price - trail_dist, Digits());
         if(new_sl > current_sl + SymbolInfoDouble(Symbol(), SYMBOL_POINT))
         {
            MqlTradeRequest req = {};
            MqlTradeResult res = {};
            req.action   = TRADE_ACTION_SLTP;
            req.position = ticket;
            req.sl       = new_sl;
            req.tp       = current_tp;
            OrderSend(req, res);
         }
      }
      else if(PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL)
      {
         new_sl = NormalizeDouble(SymbolInfoDouble(Symbol(), SYMBOL_ASK) + trail_dist, Digits());
         if(current_sl == 0 || new_sl < current_sl - SymbolInfoDouble(Symbol(), SYMBOL_POINT))
         {
            MqlTradeRequest req = {};
            MqlTradeResult res = {};
            req.action   = TRADE_ACTION_SLTP;
            req.position = ticket;
            req.sl       = new_sl;
            req.tp       = current_tp;
            OrderSend(req, res);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Session detection                                                 |
//+------------------------------------------------------------------+
bool IsGoodSession()
{
   datetime now = TimeGMT();
   MqlDateTime dt;
   TimeToStruct(now, dt);
   int hour = dt.hour;
   int min = dt.min;
   int time_mins = hour * 60 + min;
   
   // LSE: 08:00-16:30 UTC
   bool lse = (time_mins >= 480 && time_mins < 990);
   // NYSE: 13:30-20:00 UTC
   bool nyse = (time_mins >= 810 && time_mins < 1200);
   // Overlap: 13:30-16:30 UTC (best!)
   bool overlap = (time_mins >= 810 && time_mins < 990);
   
   return lse || nyse;
}

string GetSessionName()
{
   datetime now = TimeGMT();
   MqlDateTime dt;
   TimeToStruct(now, dt);
   int time_mins = dt.hour * 60 + dt.min;
   if(time_mins >= 810 && time_mins < 990) return "LDN-NY OVERLAP ⭐";
   if(time_mins >= 480 && time_mins < 990) return "LONDON";
   if(time_mins >= 810 && time_mins < 1200) return "NEW YORK";
   if(time_mins >= 0 && time_mins < 360) return "TOKYO";
   return "OFF-SESSION";
}

int GetSessionScore()
{
   datetime now = TimeGMT();
   MqlDateTime dt;
   TimeToStruct(now, dt);
   int time_mins = dt.hour * 60 + dt.min;
   if(time_mins >= 810 && time_mins < 990) return 95;  // Overlap
   if(time_mins >= 480 && time_mins < 600) return 85;  // LDN open
   if(time_mins >= 810 && time_mins < 900) return 85;  // NY open
   if(time_mins >= 600 && time_mins < 810) return 60;  // LDN mid
   return 20;
}

//+------------------------------------------------------------------+
//| Position counting                                                  |
//+------------------------------------------------------------------+
int CountPositions()
{
   int count = 0;
   for(int i = 0; i < PositionsTotal(); i++)
   {
      if(PositionGetSymbol(i) == Symbol() && 
         PositionGetInteger(POSITION_MAGIC) == Magic)
         count++;
   }
   return count;
}

bool HasPosition(ENUM_POSITION_TYPE type)
{
   for(int i = 0; i < PositionsTotal(); i++)
   {
      if(PositionGetSymbol(i) == Symbol() &&
         PositionGetInteger(POSITION_MAGIC) == Magic &&
         PositionGetInteger(POSITION_TYPE) == type)
         return true;
   }
   return false;
}

//+------------------------------------------------------------------+
//| Trade event handler                                               |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction& trans,
                        const MqlTradeRequest& req,
                        const MqlTradeResult& result)
{
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD)
   {
      if(HistoryDealSelect(trans.deal))
      {
         double profit = HistoryDealGetDouble(trans.deal, DEAL_PROFIT);
         if(profit != 0)
         {
            g_daily_pnl += profit;
            g_trades_closed++;
            string outcome = profit > 0 ? "🟢 WIN" : "🔴 LOSS";
            Print(outcome, " | Deal: ", trans.deal,
                  " | PnL: $", DoubleToString(profit, 2),
                  " | Daily: $", DoubleToString(g_daily_pnl, 2));
         }
      }
   }
}
